# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cdbbfed6655caf8cba045470064da36a533253afd6f0b80518e83d39db87af361e7635fdb277694dbd738f828b457dde94737014affd9d9fb9fa67470f27ca77

test:
  secret_key_base: 31ca363b55647911fa91e6b0f6b314db31cded8c29dbaf9c30a27a645f2468ce971b294715747641ab9967da2ded0a4145f16e50c1a2d922138c070a593e614a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
